# SAEB BASE ESCOLAS 2019
# Renato Gomes Chaves
# Criacao: 11/12/21
# Ultima edicao: 11/12/21

# Carregar Pacotes #############################################################
{
  require(pacman)
  p_load(tidyverse,
         here
  )
  # no_cores <- detectCores()
  # registerDoParallel(no_cores)
  # aumentar max mem ram com pagefile
  # utils::memory.limit(32000)
  # cat('Memoria RAM maxima:', memory.limit())
  # options(future.globals.maxSize = 2500 * 1024^2)
}

# Carregar dados ###############################################################
here('data/raw/SAEB/2019/DADOS/TS_ESCOLA.csv') %>% 
  read_delim(',',
             # n_max = 100,
             escape_double = FALSE,
             trim_ws = TRUE,
             locale = locale(encoding = "ISO-8859-1",
                             decimal_mark = ','),
             col_types = cols_only(
               ID_SAEB = 'c',
               ID_REGIAO = 'f',
               ID_UF = 'f',
               ID_MUNICIPIO = 'c',
               ID_AREA = 'f',
               ID_ESCOLA = 'c',
               ID_DEPENDENCIA_ADM = 'f',
               ID_LOCALIZACAO = 'f',
               PC_FORMACAO_DOCENTE_INICIAL = 'c',
               PC_FORMACAO_DOCENTE_FINAL = 'c',
               PC_FORMACAO_DOCENTE_MEDIO = 'c',
               NIVEL_SOCIO_ECONOMICO = 'f',
               NU_MATRICULADOS_CENSO_5EF = 'n',
               NU_PRESENTES_5EF = 'n',
               TAXA_PARTICIPACAO_5EF = 'n',
               NIVEL_0_LP5 = 'n',
               NIVEL_1_LP5 = 'n',
               NIVEL_2_LP5 = 'n',
               NIVEL_3_LP5 = 'n',
               NIVEL_4_LP5 = 'n',
               NIVEL_5_LP5 = 'n',
               NIVEL_6_LP5 = 'n',
               NIVEL_7_LP5 = 'n',
               NIVEL_8_LP5 = 'n',
               NIVEL_9_LP5 = 'n',
               NIVEL_0_MT5 = 'n',
               NIVEL_1_MT5 = 'n',
               NIVEL_2_MT5 = 'n',
               NIVEL_3_MT5 = 'n',
               NIVEL_4_MT5 = 'n',
               NIVEL_5_MT5 = 'n',
               NIVEL_6_MT5 = 'n',
               NIVEL_7_MT5 = 'n',
               NIVEL_8_MT5 = 'n',
               NIVEL_9_MT5 = 'n',
               NIVEL_10_MT5 = 'n',
               NU_MATRICULADOS_CENSO_9EF = 'n',
               NU_PRESENTES_9EF = 'n',
               TAXA_PARTICIPACAO_9EF = 'n',
               NIVEL_0_LP9 = 'n',
               NIVEL_1_LP9 = 'n',
               NIVEL_2_LP9 = 'n',
               NIVEL_3_LP9 = 'n',
               NIVEL_4_LP9 = 'n',
               NIVEL_5_LP9 = 'n',
               NIVEL_6_LP9 = 'n',
               NIVEL_7_LP9 = 'n',
               NIVEL_8_LP9 = 'n',
               NIVEL_0_MT9 = 'n',
               NIVEL_1_MT9 = 'n',
               NIVEL_2_MT9 = 'n',
               NIVEL_3_MT9 = 'n',
               NIVEL_4_MT9 = 'n',
               NIVEL_5_MT9 = 'n',
               NIVEL_6_MT9 = 'n',
               NIVEL_7_MT9 = 'n',
               NIVEL_8_MT9 = 'n',
               NIVEL_9_MT9 = 'n',
               NU_MATRICULADOS_CENSO_EMT = 'n',
               NU_PRESENTES_EMT = 'n',
               TAXA_PARTICIPACAO_EMT = 'n',
               NIVEL_0_LPEMT = 'n',
               NIVEL_1_LPEMT = 'n',
               NIVEL_2_LPEMT = 'n',
               NIVEL_3_LPEMT = 'n',
               NIVEL_4_LPEMT = 'n',
               NIVEL_5_LPEMT = 'n',
               NIVEL_6_LPEMT = 'n',
               NIVEL_7_LPEMT = 'n',
               NIVEL_8_LPEMT = 'n',
               NIVEL_0_MTEMT = 'n',
               NIVEL_1_MTEMT = 'n',
               NIVEL_2_MTEMT = 'n',
               NIVEL_3_MTEMT = 'n',
               NIVEL_4_MTEMT = 'n',
               NIVEL_5_MTEMT = 'n',
               NIVEL_6_MTEMT = 'n',
               NIVEL_7_MTEMT = 'n',
               NIVEL_8_MTEMT = 'n',
               NIVEL_9_MTEMT = 'n',
               NIVEL_10_MTEMT = 'n',
               NU_MATRICULADOS_CENSO_EMI = 'n',
               NU_PRESENTES_EMI = 'n',
               TAXA_PARTICIPACAO_EMI = 'n',
               NIVEL_0_LPEMI = 'n',
               NIVEL_1_LPEMI = 'n',
               NIVEL_2_LPEMI = 'n',
               NIVEL_3_LPEMI = 'n',
               NIVEL_4_LPEMI = 'n',
               NIVEL_5_LPEMI = 'n',
               NIVEL_6_LPEMI = 'n',
               NIVEL_7_LPEMI = 'n',
               NIVEL_8_LPEMI = 'n',
               NIVEL_0_MTEMI = 'n',
               NIVEL_1_MTEMI = 'n',
               NIVEL_2_MTEMI = 'n',
               NIVEL_3_MTEMI = 'n',
               NIVEL_4_MTEMI = 'n',
               NIVEL_5_MTEMI = 'n',
               NIVEL_6_MTEMI = 'n',
               NIVEL_7_MTEMI = 'n',
               NIVEL_8_MTEMI = 'n',
               NIVEL_9_MTEMI = 'n',
               NIVEL_10_MTEMI = 'n',
               NU_MATRICULADOS_CENSO_EM = 'n',
               NU_PRESENTES_EM = 'n',
               TAXA_PARTICIPACAO_EM = 'n',
               NIVEL_0_LPEM = 'n',
               NIVEL_1_LPEM = 'n',
               NIVEL_2_LPEM = 'n',
               NIVEL_3_LPEM = 'n',
               NIVEL_4_LPEM = 'n',
               NIVEL_5_LPEM = 'n',
               NIVEL_6_LPEM = 'n',
               NIVEL_7_LPEM = 'n',
               NIVEL_8_LPEM = 'n',
               NIVEL_0_MTEM = 'n',
               NIVEL_1_MTEM = 'n',
               NIVEL_2_MTEM = 'n',
               NIVEL_3_MTEM = 'n',
               NIVEL_4_MTEM = 'n',
               NIVEL_5_MTEM = 'n',
               NIVEL_6_MTEM = 'n',
               NIVEL_7_MTEM = 'n',
               NIVEL_8_MTEM = 'n',
               NIVEL_9_MTEM = 'n',
               NIVEL_10_MTEM = 'n',
               MEDIA_5EF_LP = 'n',
               MEDIA_5EF_MT = 'n',
               MEDIA_9EF_LP = 'n',
               MEDIA_9EF_MT = 'n',
               MEDIA_EMT_LP = 'n',
               MEDIA_EMT_MT = 'n',
               MEDIA_EMI_LP = 'n',
               MEDIA_EMI_MT = 'n',
               MEDIA_EM_LP = 'n',
               MEDIA_EM_MT = 'n'
             )
  ) %>% 
  {. ->> saeb_2019_escola}

# Renomear niveis dos fatores #################################################
saeb_2019_escola %>%
  mutate(ID_REGIAO = recode(ID_REGIAO,
                            `1` = 'Norte',
                            `2` = 'Nordeste',
                            `3` = 'Sudeste',
                            `4` = 'Sul',
                            `5` = 'Centro-Oeste'),
         ID_UF = recode(ID_UF,
                        `11` = 'RO',
                        `12` = 'AC',
                        `13` = 'AM',
                        `14` = 'RR',
                        `15` = 'PA',
                        `16` = 'AP',
                        `17` = 'TO',
                        `21` = 'MA',
                        `22` = 'PI',
                        `23` = 'CE',
                        `24` = 'RN',
                        `25` = 'PB',
                        `26` = 'PE',
                        `27` = 'AL',
                        `28` = 'SE',
                        `29` = 'BA',
                        `31` = 'MG',
                        `32` = 'ES',
                        `33` = 'RJ',
                        `35` = 'SP',
                        `41` = 'PR',
                        `42` = 'SC',
                        `43` = 'RS',
                        `50` = 'MS',
                        `51` = 'MT',
                        `52` = 'GO',
                        `53` = 'DF'),
         ID_AREA = recode(ID_AREA,
                          `1` = 'Capital',
                          `2` = 'Interior'),
         ID_DEPENDENCIA_ADM = recode(ID_DEPENDENCIA_ADM,
                                     `1`  =  'Federal',
                                     `2`  =  'Estadual',
                                     `3`  =  'Municipal',
                                     `4`  =  'Privada'),
         ID_LOCALIZACAO = recode(ID_LOCALIZACAO,
                                 `1`  =  'Urbana',
                                 `2`  =  'Rural')
         ) %>% 
  {. ->> saeb_2019_escola}

# Salvar dados limpos ##########################################################
saeb_2019_escola %>% 
  saveRDS(here('data/processed/SAEB/saeb_2019_escola.rds'))