# SAEB BASE PROFESSORES 2019
# Renato Gomes Chaves
# Criacao: 11/12/21
# Ultima edicao: 13/12/21

# Carregar Pacotes #############################################################
{
  require(pacman)
  p_load(tidyverse,
         here
  )
  # no_cores <- detectCores()
  # registerDoParallel(no_cores)
  # aumentar max mem ram com pagefile
  # utils::memory.limit(32000)
  # cat('Memoria RAM maxima:', memory.limit())
  # options(future.globals.maxSize = 2500 * 1024^2)
}

# Carregar dados ###############################################################
here('data/raw/SAEB/2019/DADOS/TS_PROFESSOR.csv') %>% 
  read_delim(',',
             # n_max = 100,
             escape_double = FALSE,
             trim_ws = TRUE,
             locale = locale(encoding = "ISO-8859-1",
                             decimal_mark = ','),
             col_types = cols_only(
               ID_SAEB = 'c',
               ID_REGIAO = 'f',
               ID_UF = 'f',
               ID_MUNICIPIO = 'c',
               ID_AREA = 'f',
               ID_ESCOLA = 'c',
               ID_DEPENDENCIA_ADM = 'f',
               ID_LOCALIZACAO = 'f',
               ID_TURMA = 'c',
               CO_PROFESSOR = 'c',
               ID_SERIE = 'f',
               IN_PREENCHIMENTO_QUESTIONARIO = 'f',
############## Perguntas do questionario
               TX_RESP_Q001 = 'c',
               TX_RESP_Q002 = 'c',
               TX_RESP_Q003 = 'c',
               TX_RESP_Q004 = 'c',
               TX_RESP_Q005 = 'c',
               TX_RESP_Q006 = 'c',
               TX_RESP_Q007 = 'c',
               TX_RESP_Q008 = 'c',
               TX_RESP_Q009 = 'c',
               TX_RESP_Q010 = 'c',
               TX_RESP_Q011 = 'c',
               TX_RESP_Q012 = 'c',
               TX_RESP_Q013 = 'c',
               TX_RESP_Q014 = 'c',
               TX_RESP_Q015 = 'c',
               TX_RESP_Q016 = 'c',
               TX_RESP_Q017 = 'c',
               TX_RESP_Q018 = 'c',
               TX_RESP_Q019 = 'c',
               TX_RESP_Q020 = 'c',
               TX_RESP_Q021 = 'c',
               TX_RESP_Q022 = 'c',
               TX_RESP_Q023 = 'c',
               TX_RESP_Q024 = 'c',
               TX_RESP_Q025 = 'c',
               TX_RESP_Q026 = 'c',
               TX_RESP_Q027 = 'c',
               TX_RESP_Q028 = 'c',
               TX_RESP_Q029 = 'c',
               TX_RESP_Q030 = 'c',
               TX_RESP_Q031 = 'c',
               TX_RESP_Q032 = 'c',
               TX_RESP_Q033 = 'c',
               TX_RESP_Q034 = 'c',
               TX_RESP_Q035 = 'c',
               TX_RESP_Q036 = 'c',
               TX_RESP_Q037 = 'c',
               TX_RESP_Q038 = 'c',
               TX_RESP_Q039 = 'c',
               TX_RESP_Q040 = 'c',
               TX_RESP_Q041 = 'c',
               TX_RESP_Q042 = 'c',
               TX_RESP_Q043 = 'c',
               TX_RESP_Q044 = 'c',
               TX_RESP_Q045 = 'c',
               TX_RESP_Q046 = 'c',
               TX_RESP_Q047 = 'c',
               TX_RESP_Q048 = 'c',
               TX_RESP_Q049 = 'c',
               TX_RESP_Q050 = 'c',
               TX_RESP_Q051 = 'c',
               TX_RESP_Q052 = 'c',
               TX_RESP_Q053 = 'c',
               TX_RESP_Q054 = 'c',
               TX_RESP_Q055 = 'c',
               TX_RESP_Q056 = 'c',
               TX_RESP_Q057 = 'c',
               TX_RESP_Q058 = 'c',
               TX_RESP_Q059 = 'c',
               TX_RESP_Q060 = 'c',
               TX_RESP_Q061 = 'c',
               TX_RESP_Q062 = 'c',
               TX_RESP_Q063 = 'c',
               TX_RESP_Q064 = 'c',
               TX_RESP_Q065 = 'c',
               TX_RESP_Q066 = 'c',
               TX_RESP_Q067 = 'c',
               TX_RESP_Q068 = 'c',
               TX_RESP_Q069 = 'c',
               TX_RESP_Q070 = 'c',
               TX_RESP_Q071 = 'c',
               TX_RESP_Q072 = 'c',
               TX_RESP_Q073 = 'c',
               TX_RESP_Q074 = 'c',
               TX_RESP_Q075 = 'c',
               TX_RESP_Q076 = 'c',
               TX_RESP_Q077 = 'c',
               TX_RESP_Q078 = 'c',
               TX_RESP_Q079 = 'c',
               TX_RESP_Q080 = 'c',
               TX_RESP_Q081 = 'c',
               TX_RESP_Q082 = 'c',
               TX_RESP_Q083 = 'c',
               TX_RESP_Q084 = 'c',
               TX_RESP_Q085 = 'c',
               TX_RESP_Q086 = 'c',
               TX_RESP_Q087 = 'c',
               TX_RESP_Q088 = 'c',
               TX_RESP_Q089 = 'c',
               TX_RESP_Q090 = 'c',
               TX_RESP_Q091 = 'c',
               TX_RESP_Q092 = 'c',
               TX_RESP_Q093 = 'c',
               TX_RESP_Q094 = 'c',
               TX_RESP_Q095 = 'c',
               TX_RESP_Q096 = 'c',
               TX_RESP_Q097 = 'c',
               TX_RESP_Q098 = 'c',
               TX_RESP_Q099 = 'c',
               TX_RESP_Q100 = 'c',
               TX_RESP_Q101 = 'c',
               TX_RESP_Q102 = 'c',
               TX_RESP_Q103 = 'c',
               TX_RESP_Q104 = 'c',
               TX_RESP_Q105 = 'c',
               TX_RESP_Q106 = 'c',
               TX_RESP_Q107 = 'c',
               TX_RESP_Q108 = 'c',
               TX_RESP_Q109 = 'c',
               TX_RESP_Q110 = 'c',
               TX_RESP_Q111 = 'c',
               TX_RESP_Q112 = 'c',
               TX_RESP_Q113 = 'c',
               TX_RESP_Q114 = 'c',
               TX_RESP_Q115 = 'c',
               TX_RESP_Q116 = 'c',
               TX_RESP_Q117 = 'c',
               TX_RESP_Q118 = 'c',
               TX_RESP_Q119 = 'c',
               TX_RESP_Q120 = 'c',
               TX_RESP_Q121 = 'c',
               TX_RESP_Q122 = 'c',
               TX_RESP_Q123 = 'c',
               TX_RESP_Q124 = 'c',
               TX_RESP_Q125 = 'c',
               TX_RESP_Q126 = 'c',
               TX_RESP_Q127 = 'c',
               TX_RESP_Q128 = 'c'
             )
  ) %>% 
  {. ->> saeb_2019_professor}

# Renomear niveis dos fatores #################################################
# pegar os titulos das perguntas dos questionarios
here('data/raw/SAEB/2019/DICIONÁRIO/Dicionario_Saeb_2019.xlsx') %>% 
  readxl::read_excel(sheet = 7, 
                     skip = 54) %>% 
  select(texto_perguntas = `Descrição (texto da pergunta)`) %>% 
  drop_na() %>%
  pull(texto_perguntas) %>% 
  {. ->> var_names}
  

# renomear respostas dos questionarios
saeb_2019_professor %>% 
  mutate(ID_REGIAO = factor(ID_REGIAO,
                            levels = c(1, 2, 3, 4, 5),
                            labels = c( 'Norte',
                                        'Nordeste',
                                        'Sudeste',
                                        'Sul',
                                        'Centro-Oeste')
                            ),
         ID_UF = factor(ID_UF,
                        levels = c(11, 12, 13, 14, 15, 16, 17, 21, 22, 23, 24, 25, 26,
                                    27, 28, 29, 31, 32, 33, 35, 41, 42, 43, 50, 51, 52,
                                    53), 
                        labels = c( 'RO', 'AC', 'AM', 'RR', 'PA', 'AP', 'TO', 'MA', 'PI',
                                    'CE', 'RN', 'PB', 'PE', 'AL', 'SE', 'BA', 'MG', 'ES',
                                    'RJ', 'SP', 'PR', 'SC', 'RS', 'MS', 'MT', 'GO', 'DF')
                        ),
        ID_AREA = factor(ID_AREA,
                         levels = c(1, 2),
                         labels = c( 'Capital',
                                     'Interior')
                         ),
        ID_DEPENDENCIA_ADM = factor(ID_DEPENDENCIA_ADM,
                                    levels = c(1,2,3,4),
                                    labels = c('Federal',
                                               'Estadual',
                                               'Municipal',
                                               'Privada')
                                    ),
        ID_LOCALIZACAO = factor(ID_LOCALIZACAO,
                                levels = c(1, 2),
                                labels = c('Urbana',
                                           'Rural')
                                ),
        ID_SERIE = factor(ID_SERIE, levels = c(5, 9, 12, 13),
                          labels = c('5º ano do Ensino Fundamental',
                                     '9º ano do Ensino Fundamental',
                                     '3ª/4ª séries do Ensino Médio Tradicional',
                                     '3ª/4ª séries do Ensino Médio Integrado')
                          ),
        IN_PREENCHIMENTO_QUESTIONARIO = factor(IN_PREENCHIMENTO_QUESTIONARIO,
                                               levels = c(0, 1),
                                               labels = c('Não preenchido',
                                                          'Preenchido parcial ou totalmente')
                                               ),
        TX_RESP_Q001 = factor(TX_RESP_Q001,
                              levels = c('A', 'B', 'C', 'D', 'E', 'F'),
                              labels = c( 'Branca',
                                          'Preta',
                                          'Parda',
                                          'Amarela',
                                          'Indígena',
                                          'Não quero declarar')
                              ),
        TX_RESP_Q002 = factor(TX_RESP_Q002,
                              levels = c('A','B','C','D','E','F','G'),
                              labels = c( 'Meu primeiro ano.',
                                          '1-2 anos.',
                                          '3-5 anos.',
                                          '6-10 anos.',
                                          '11-15 anos.',
                                          '16-20 anos.',
                                          'Mais de 20 anos.')
                              ),
        TX_RESP_Q003 = factor(TX_RESP_Q003,
                              levels = c('A','B','C','D','E','F','G'),
                              labels = c( 'Meu primeiro ano.',
                                          '1-2 anos.',
                                          '3-5 anos.',
                                          '6-10 anos.',
                                          '11-15 anos.',
                                          '16-20 anos.',
                                          'Mais de 20 anos.')
                              ),
        TX_RESP_Q004 = factor(TX_RESP_Q004,
                              levels = c('A','B','C','D'),
                              labels = c( ' Apenas nesta.', ' Em 2.', ' Em 3.', ' Em 4 ou mais.')),
        TX_RESP_Q005 = factor(TX_RESP_Q005,
                              levels = c('A','B','C','D','E','F'),
                              labels = c( ' Concursado/efetivo/estável.', ' Contrato temporário.', ' Contrato terceirizado.', ' Contrato CLT.', ' Pessoa jurídica.', ' Outra situação trabalhista.')),
        TX_RESP_Q006 = factor(TX_RESP_Q006,
                              levels = c('A','B','C','D'),
                              labels = c( 'Discordo fortemente.', 'Discordo.', 'Concordo.', 'Concordo fortemente.')),
        TX_RESP_Q007 = factor(TX_RESP_Q007,
                              levels = c('A','B','C','D'),
                              labels = c( 'Discordo fortemente.', 'Discordo.', 'Concordo.', 'Concordo fortemente.')),
        TX_RESP_Q008 = factor(TX_RESP_Q008,
                              levels = c('A','B','C','D'),
                              labels = c( 'Discordo fortemente.', 'Discordo.', 'Concordo.', 'Concordo fortemente.')),
        TX_RESP_Q009 = factor(TX_RESP_Q009,
                              levels = c('A','B','C','D'),
                              labels = c( 'Discordo fortemente.', 'Discordo.', 'Concordo.', 'Concordo fortemente.')),
        TX_RESP_Q010 = factor(TX_RESP_Q010,
                              levels = c('A','B','C','D'),
                              labels = c( 'Discordo fortemente.', 'Discordo.', 'Concordo.', 'Concordo fortemente.')),
        TX_RESP_Q011 = factor(TX_RESP_Q011,
                              levels = c('A','B','C','D'),
                              labels = c( 'Discordo fortemente.', 'Discordo.', 'Concordo.', 'Concordo fortemente.')),
        TX_RESP_Q012 = factor(TX_RESP_Q012,
                              levels = c('A','B','C','D'),
                              labels = c( 'Discordo fortemente.', 'Discordo.', 'Concordo.', 'Concordo fortemente.')),
        TX_RESP_Q013 = factor(TX_RESP_Q013,
                              levels = c('A','B','C','D'),
                              labels = c( 'Discordo fortemente.', 'Discordo.', 'Concordo.', 'Concordo fortemente.')),
        TX_RESP_Q014 = factor(TX_RESP_Q014,
                              levels = c('A','B','C','D'),
                              labels = c( 'Discordo fortemente.', 'Discordo.', 'Concordo.', 'Concordo fortemente.')),
        TX_RESP_Q015 = factor(TX_RESP_Q015,
                              levels = c('A','B','C','D'),
                              labels = c( 'Nunca.', 'Poucas vezes.', 'Muitas vezes.', 'Sempre.')),
        TX_RESP_Q016 = factor(TX_RESP_Q016,
                              levels = c('A','B','C','D'),
                              labels = c( 'Nunca.', 'Poucas vezes.', 'Muitas vezes.', 'Sempre.')),
        TX_RESP_Q017 = factor(TX_RESP_Q017,
                              levels = c('A','B','C','D'),
                              labels = c( 'Nunca.', 'Poucas vezes.', 'Muitas vezes.', 'Sempre.')),
        TX_RESP_Q018 = factor(TX_RESP_Q018,
                              levels = c('A','B','C','D'),
                              labels = c( 'Nunca.', 'Poucas vezes.', 'Muitas vezes.', 'Sempre.')),
        TX_RESP_Q019 = factor(TX_RESP_Q019,
                              levels = c('A','B','C','D'),
                              labels = c( 'Nunca.', 'Poucas vezes.', 'Muitas vezes.', 'Sempre.')),
        TX_RESP_Q020 = factor(TX_RESP_Q020,
                              levels = c('A','B','C','D'),
                              labels = c( 'Nunca.', 'Poucas vezes.', 'Muitas vezes.', 'Sempre.')),
        TX_RESP_Q021 = factor(TX_RESP_Q021,
                              levels = c('A','B','C','D'),
                              labels = c( 'Nunca.', 'Poucas vezes.', 'Muitas vezes.', 'Sempre.')),
        TX_RESP_Q022 = factor(TX_RESP_Q022,
                              levels = c('A','B','C','D'),
                              labels = c( 'Nunca.', 'Poucas vezes.', 'Muitas vezes.', 'Sempre.')),
        TX_RESP_Q023 = factor(TX_RESP_Q023,
                              levels = c('A','B','C','D'),
                              labels = c( 'Inadequado.', 'Pouco adequado.', 'Razoavelmente adequado.', 'Adequado.')),
        TX_RESP_Q024 = factor(TX_RESP_Q024,
                              levels = c('A','B','C','D'),
                              labels = c( 'Inadequado.', 'Pouco adequado.', 'Razoavelmente adequado.', 'Adequado.')),
        TX_RESP_Q025 = factor(TX_RESP_Q025,
                              levels = c('A','B','C','D'),
                              labels = c( 'Inadequado.', 'Pouco adequado.', 'Razoavelmente adequado.', 'Adequado.')),
        TX_RESP_Q026 = factor(TX_RESP_Q026,
                              levels = c('A','B','C','D'),
                              labels = c( 'Inadequado.', 'Pouco adequado.', 'Razoavelmente adequado.', 'Adequado.')),
        TX_RESP_Q027 = factor(TX_RESP_Q027,
                              levels = c('A','B','C','D'),
                              labels = c( 'Inadequado.', 'Pouco adequado.', 'Razoavelmente adequado.', 'Adequado.')),
        TX_RESP_Q028 = factor(TX_RESP_Q028,
                              levels = c('A','B','C','D'),
                              labels = c( 'Inadequado.', 'Pouco adequado.', 'Razoavelmente adequado.', 'Adequado.')),
        TX_RESP_Q029 = factor(TX_RESP_Q029,
                              levels = c('A','B','C','D'),
                              labels = c( 'Inadequado.', 'Pouco adequado.', 'Razoavelmente adequado.', 'Adequado.')),
        TX_RESP_Q030 = factor(TX_RESP_Q030,
                              levels = c('A','B','C','D'),
                              labels = c( 'Inadequado.', 'Pouco adequado.', 'Razoavelmente adequado.', 'Adequado.')),
        TX_RESP_Q031 = factor(TX_RESP_Q031,
                              levels = c('A','B','C','D'),
                              labels = c( 'Inadequado.', 'Pouco adequado.', 'Razoavelmente adequado.', 'Adequado.')),
        TX_RESP_Q032 = factor(TX_RESP_Q032,
                              levels = c('A','B','C','D'),
                              labels = c( 'Inadequado.', 'Pouco adequado.', 'Razoavelmente adequado.', 'Adequado.')),
        TX_RESP_Q033 = factor(TX_RESP_Q033,
                              levels = c('A','B','C','D','E'),
                              labels = c( 'NÃO USO / Não tem.', 'USO E É Inadequado.', 'USO E É Pouco adequado.', 'USO E É Razoavelmente adequado.', 'USO E É Adequado.')),
        TX_RESP_Q034 = factor(TX_RESP_Q034,
                              levels = c('A','B','C','D','E'),
                              labels = c( 'NÃO USO / Não tem.', 'USO E É Inadequado.', 'USO E É Pouco adequado.', 'USO E É Razoavelmente adequado.', 'USO E É Adequado.')),
        TX_RESP_Q035 = factor(TX_RESP_Q035,
                              levels = c('A','B','C','D','E'),
                              labels = c( 'NÃO USO / Não tem.', 'USO E É Inadequado.', 'USO E É Pouco adequado.', 'USO E É Razoavelmente adequado.', 'USO E É Adequado.')),
        TX_RESP_Q036 = factor(TX_RESP_Q036,
                              levels = c('A','B','C','D','E'),
                              labels = c( 'NÃO USO / Não tem.', 'USO E É Inadequado.', 'USO E É Pouco adequado.', 'USO E É Razoavelmente adequado.', 'USO E É Adequado.')),
        TX_RESP_Q037 = factor(TX_RESP_Q037,
                              levels = c('A','B','C','D','E'),
                              labels = c( 'NÃO USO / Não tem.', 'USO E É Inadequado.', 'USO E É Pouco adequado.', 'USO E É Razoavelmente adequado.', 'USO E É Adequado.')),
        TX_RESP_Q038 = factor(TX_RESP_Q038,
                              levels = c('A','B','C','D','E'),
                              labels = c( 'NÃO USO / Não tem.', 'USO E É Inadequado.', 'USO E É Pouco adequado.', 'USO E É Razoavelmente adequado.', 'USO E É Adequado.')),
        TX_RESP_Q039 = factor(TX_RESP_Q039,
                              levels = c('A','B','C','D','E'),
                              labels = c( 'Até 10 horas.', 'De 11 a 20 horas.', 'De 21 a 30 horas.', 'De 31 a 40 horas.', 'Mais de 40 horas.')),
        TX_RESP_Q040 = factor(TX_RESP_Q040,
                              levels = c('A','B','C','D','E'),
                              labels = c( 'Até 10 horas.', 'De 11 a 20 horas.', 'De 21 a 30 horas.', 'De 31 a 40 horas.', 'Mais de 40 horas.')),
        TX_RESP_Q041 = factor(TX_RESP_Q041, 
                              levels = c('A','B','C','D','E'),
                              labels = c( 'Até 10 horas.', 'De 11 a 20 horas.', 'De 21 a 30 horas.', 'De 31 a 40 horas.', 'Mais de 40 horas.')),
        TX_RESP_Q042 = factor(TX_RESP_Q042,
                              levels = c('A','B','C','D'),
                              labels = c( 'Nada preparado(a).', 'Pouco preparado(a).', 'Razoavelmente preparado(a).', 'Muito preparado(a).')),
        TX_RESP_Q043 = factor(TX_RESP_Q043,
                              levels = c('A','B','C','D'),
                              labels = c( 'Nada preparado(a).', 'Pouco preparado(a).', 'Razoavelmente preparado(a).', 'Muito preparado(a).')),
        TX_RESP_Q044 = factor(TX_RESP_Q044,
                              levels = c('A','B','C','D'),
                              labels = c( 'Nada preparado(a).', 'Pouco preparado(a).', 'Razoavelmente preparado(a).', 'Muito preparado(a).')),
        TX_RESP_Q045 = factor(TX_RESP_Q045,
                              levels = c('A','B','C','D'),
                              labels = c( 'Nada preparado(a).', 'Pouco preparado(a).', 'Razoavelmente preparado(a).', 'Muito preparado(a).')),
        TX_RESP_Q046 = factor(TX_RESP_Q046,
                              levels = c('A','B','C','D'),
                              labels = c( 'Nada preparado(a).', 'Pouco preparado(a).', 'Razoavelmente preparado(a).', 'Muito preparado(a).')),
        TX_RESP_Q047 = factor(TX_RESP_Q047, 
                              levels = c('A','B','C','D'),
                              labels = c( 'Nada preparado(a).', 'Pouco preparado(a).', 'Razoavelmente preparado(a).', 'Muito preparado(a).')),
        TX_RESP_Q048 = factor(TX_RESP_Q048,
                              levels = c('A','B','C','D'),
                              labels = c( 'Nada preparado(a).', 'Pouco preparado(a).', 'Razoavelmente preparado(a).', 'Muito preparado(a).')),
        TX_RESP_Q049 = factor(TX_RESP_Q049,
                              levels = c('A','B','C','D'),
                              labels = c( 'Nada preparado(a).', 'Pouco preparado(a).', 'Razoavelmente preparado(a).', 'Muito preparado(a).')),
        TX_RESP_Q050 = factor(TX_RESP_Q050,
                              levels = c('A','B','C','D'),
                              labels = c( 'Nada preparado(a).', 'Pouco preparado(a).', 'Razoavelmente preparado(a).', 'Muito preparado(a).')),
        TX_RESP_Q051 = factor(TX_RESP_Q051, 
                              levels = c('A','B','C','D'),
                              labels = c( 'Nada preparado(a).', 'Pouco preparado(a).', 'Razoavelmente preparado(a).', 'Muito preparado(a).')),
        TX_RESP_Q052 = factor(TX_RESP_Q052,
                              levels = c('A','B','C','D'),
                              labels = c( 'Nada preparado(a).', 'Pouco preparado(a).', 'Razoavelmente preparado(a).', 'Muito preparado(a).')),
        TX_RESP_Q053 = factor(TX_RESP_Q053,
                              levels = c('A','B','C','D'),
                              labels = c( 'Nenhuma.', 'Uma.', 'Duas.', 'Três ou mais.')),
        TX_RESP_Q054 = factor(TX_RESP_Q054,
                              levels = c('A','B','C','D'),
                              labels = c( 'Nenhuma.', 'Uma.', 'Duas.', 'Três ou mais.')),
        TX_RESP_Q055 = factor(TX_RESP_Q055, 
                              levels = c('A','B','C','D'),
                              labels = c( 'Nenhuma.', 'Uma.', 'Duas.', 'Três ou mais.')),
        TX_RESP_Q056 = factor(TX_RESP_Q056,
                              levels = c('A','B','C','D'),
                              labels = c( 'Nunca.', 'Poucas vezes.', 'Muitas vezes.', 'Sempre.')),
        TX_RESP_Q057 = factor(TX_RESP_Q057,
                              levels = c('A','B','C','D'),
                              labels = c( 'Nunca.', 'Poucas vezes.', 'Muitas vezes.', 'Sempre.')),
        TX_RESP_Q058 = factor(TX_RESP_Q058, 
                              levels = c('A','B','C','D'),
                              labels = c( 'Nunca.', 'Poucas vezes.', 'Muitas vezes.', 'Sempre.')),
        TX_RESP_Q059 = factor(TX_RESP_Q059, 
                              levels = c('A','B','C','D'),
                              labels = c( 'Não fiz este curso.', 'Sim, sem apoio.', 'Sim, com apoio parcial.', 'Sim, com apoio total.')),
        TX_RESP_Q060 = factor(TX_RESP_Q060,
                              levels = c('A','B','C','D'),
                              labels = c( 'Não fiz este curso.', 'Sim, sem apoio.', 'Sim, com apoio parcial.', 'Sim, com apoio total.')),
        TX_RESP_Q061 = factor(TX_RESP_Q061, 
                              levels = c('A','B','C','D'),
                              labels = c( 'Não fiz este curso.', 'Sim, sem apoio.', 'Sim, com apoio parcial.', 'Sim, com apoio total.')),
        TX_RESP_Q062 = factor(TX_RESP_Q062,
                              levels = c('A','B','C','D'),
                              labels = c( 'Não contribuiu.', 'Contribuiu pouco.', 'Contribuiu razoavelmente.', 'Contribuiu muito.')),
        TX_RESP_Q063 = factor(TX_RESP_Q063,
                              levels = c('A','B','C','D'),
                              labels = c( 'Não contribuiu.', 'Contribuiu pouco.', 'Contribuiu razoavelmente.', 'Contribuiu muito.')),
        TX_RESP_Q064 = factor(TX_RESP_Q064,
                              levels = c('A','B','C','D'),
                              labels = c( 'Não contribuiu.', 'Contribuiu pouco.', 'Contribuiu razoavelmente.', 'Contribuiu muito.')),
        TX_RESP_Q065 = factor(TX_RESP_Q065,
                              levels = c('A','B','C','D'),
                              labels = c( 'Não contribuiu.', 'Contribuiu pouco.', 'Contribuiu razoavelmente.', 'Contribuiu muito.')),
        TX_RESP_Q066 = factor(TX_RESP_Q066,
                              levels = c('A','B','C','D'),
                              labels = c( 'Não contribuiu.', 'Contribuiu pouco.', 'Contribuiu razoavelmente.', 'Contribuiu muito.')),
        TX_RESP_Q067 = factor(TX_RESP_Q067,
                              levels = c('A','B','C','D'),
                              labels = c( 'Não contribuiu.', 'Contribuiu pouco.', 'Contribuiu razoavelmente.', 'Contribuiu muito.')),
        TX_RESP_Q068 = factor(TX_RESP_Q068,
                              levels = c('A','B','C','D'),
                              labels = c( 'Não contribuiu.', 'Contribuiu pouco.', 'Contribuiu razoavelmente.', 'Contribuiu muito.')),
        TX_RESP_Q069 = factor(TX_RESP_Q069,
                              levels = c('A','B','C','D'),
                              labels = c( 'Docente da turma.', 'Todo o corpo docente da escola.', 'Equipe gestora.', 'Decisão externa à escola.')),
        TX_RESP_Q070 = factor(TX_RESP_Q070,
                              levels = c('A','B','C','D'),
                              labels = c( 'Docente da turma.', 'Todo o corpo docente da escola.', 'Equipe gestora.', 'Decisão externa à escola.')),
        TX_RESP_Q071 = factor(TX_RESP_Q071,
                              levels = c('A','B','C','D'),
                              labels = c( 'Docente da turma.', 'Todo o corpo docente da escola.', 'Equipe gestora.', 'Decisão externa à escola.')),
        TX_RESP_Q072 = factor(TX_RESP_Q072,
                              levels = c('A','B','C','D'),
                              labels = c( 'Docente da turma.', 'Todo o corpo docente da escola.', 'Equipe gestora.', 'Decisão externa à escola.')),
        TX_RESP_Q073 = factor(TX_RESP_Q073,
                              levels = c('A','B','C','D'),
                              labels = c( 'Docente da turma.', 'Todo o corpo docente da escola.', 'Equipe gestora.', 'Decisão externa à escola.')),
        TX_RESP_Q074 = factor(TX_RESP_Q074,
                              levels = c('A','B','C','D'),
                              labels = c( 'Docente da turma.', 'Todo o corpo docente da escola.', 'Equipe gestora.', 'Decisão externa à escola.')),
        TX_RESP_Q075 = factor(TX_RESP_Q075,
                              levels = c('A','B','C'),
                              labels = c( 'Desconheço o projeto.', 'Não.', 'Sim.')),
        TX_RESP_Q076 = factor(TX_RESP_Q076,
                              levels = c('A','B','C'),
                              labels = c( 'Desconheço o projeto.', 'Não.', 'Sim.')),
        TX_RESP_Q077 = factor(TX_RESP_Q077,
                              levels = c('A','B','C'),
                              labels = c( 'Desconheço o projeto.', 'Não.', 'Sim.')),
        TX_RESP_Q078 = factor(TX_RESP_Q078,
                              levels = c('A','B','C'),
                              labels = c( 'Desconheço o projeto.', 'Não.', 'Sim.')),
        TX_RESP_Q079 = factor(TX_RESP_Q079,
                              levels = c('A','B','C'),
                              labels = c( 'Desconheço o projeto.', 'Não.', 'Sim.')),
        TX_RESP_Q080 = factor(TX_RESP_Q080,
                              levels = c('A','B','C','D','E'),
                              labels = c( ' Não existe Conselho de Classe nesta escola.', ' Nenhuma vez.', ' Uma vez.', ' Duas vezes.', ' Três vezes ou mais.')),
        TX_RESP_Q081 = factor(TX_RESP_Q081,
                              levels = c('A','B','C','D'),
                              labels = c( 'Discordo fortemente.', 'Discordo.', 'Concordo.', 'Concordo fortemente.')),
        TX_RESP_Q082 = factor(TX_RESP_Q082,
                              levels = c('A','B','C','D'),
                              labels = c( 'Discordo fortemente.', 'Discordo.', 'Concordo.', 'Concordo fortemente.')),
        TX_RESP_Q083 = factor(TX_RESP_Q083,
                              levels = c('A','B','C','D'),
                              labels = c( 'Discordo fortemente.', 'Discordo.', 'Concordo.', 'Concordo fortemente.')),
        TX_RESP_Q084 = factor(TX_RESP_Q084,
                              levels = c('A','B','C','D'),
                              labels = c( 'Discordo fortemente.', 'Discordo.', 'Concordo.', 'Concordo fortemente.')),
        TX_RESP_Q085 = factor(TX_RESP_Q085,
                              levels = c('A','B','C','D'),
                              labels = c( 'Discordo fortemente.', 'Discordo.', 'Concordo.', 'Concordo fortemente.')),
        TX_RESP_Q086 = factor(TX_RESP_Q086,
                              levels = c('A','B','C','D'),
                              labels = c( 'Discordo fortemente.', 'Discordo.', 'Concordo.', 'Concordo fortemente.')),
        TX_RESP_Q087 = factor(TX_RESP_Q087,
                              levels = c('A','B','C','D'),
                              labels = c( 'Discordo fortemente.', 'Discordo.', 'Concordo.', 'Concordo fortemente.')),
        TX_RESP_Q088 = factor(TX_RESP_Q088,
                              levels = c('A','B','C','D'),
                              labels = c( 'Discordo fortemente.', 'Discordo.', 'Concordo.', 'Concordo fortemente.')),
        TX_RESP_Q089 = factor(TX_RESP_Q089,
                              levels = c('A','B','C','D'),
                              labels = c( 'Nunca.', 'Poucas vezes.', 'Muitas vezes.', 'Sempre.')),
        TX_RESP_Q090 = factor(TX_RESP_Q090,
                              levels = c('A','B','C','D'),
                              labels = c( 'Nunca.', 'Poucas vezes.', 'Muitas vezes.', 'Sempre.')),
        TX_RESP_Q091 = factor(TX_RESP_Q091,
                              levels = c('A','B','C','D'),
                              labels = c( 'Nunca.', 'Poucas vezes.', 'Muitas vezes.', 'Sempre.')),
        TX_RESP_Q092 = factor(TX_RESP_Q092,
                              levels = c('A','B','C','D'),
                              labels = c( 'Nunca.', 'Poucas vezes.', 'Muitas vezes.', 'Sempre.')),
        TX_RESP_Q093 = factor(TX_RESP_Q093,
                              levels = c('A','B','C','D'),
                              labels = c( 'Nunca.', 'Poucas vezes.', 'Muitas vezes.', 'Sempre.')),
        TX_RESP_Q094 = factor(TX_RESP_Q094,
                              levels = c('A','B','C','D'),
                              labels = c( 'Discordo fortemente.', 'Discordo.', 'Concordo.', 'Concordo fortemente.')),
        TX_RESP_Q095 = factor(TX_RESP_Q095,
                              levels = c('A','B','C','D'),
                              labels = c( 'Discordo fortemente.', 'Discordo.', 'Concordo.', 'Concordo fortemente.')),
        TX_RESP_Q096 = factor(TX_RESP_Q096,
                              levels = c('A','B','C','D'),
                              labels = c( 'Discordo fortemente.', 'Discordo.', 'Concordo.', 'Concordo fortemente.')),
        TX_RESP_Q097 = factor(TX_RESP_Q097,
                              levels = c('A','B','C','D'),
                              labels = c( 'Discordo fortemente.', 'Discordo.', 'Concordo.', 'Concordo fortemente.')),
        TX_RESP_Q098 = factor(TX_RESP_Q098,
                              levels = c('A','B','C','D'),
                              labels = c( 'Discordo fortemente.', 'Discordo.', 'Concordo.', 'Concordo fortemente.')),
        TX_RESP_Q099 = factor(TX_RESP_Q099,
                              levels = c('A','B','C','D'),
                              labels = c( 'Discordo fortemente.', 'Discordo.', 'Concordo.', 'Concordo fortemente.')),
        TX_RESP_Q100 = factor(TX_RESP_Q100,
                              levels = c('A','B','C'),
                              labels = c( 'Nunca.', 'Poucas vezes.', 'Várias vezes.')),
        TX_RESP_Q101 = factor(TX_RESP_Q101,
                              levels = c('A','B','C'),
                              labels = c( 'Nunca.', 'Poucas vezes.', 'Várias vezes.')),
        TX_RESP_Q102 = factor(TX_RESP_Q102, 
                              levels = c('A','B','C'),
                              labels = c( 'Nunca.', 'Poucas vezes.', 'Várias vezes.')),
        TX_RESP_Q103 = factor(TX_RESP_Q103,
                              levels = c('A','B','C'),
                              labels = c( 'Nunca.', 'Poucas vezes.', 'Várias vezes.')),
        TX_RESP_Q104 = factor(TX_RESP_Q104,
                              levels = c('A','B','C'),
                              labels = c( 'Nunca.', 'Poucas vezes.', 'Várias vezes.')),
        TX_RESP_Q105 = factor(TX_RESP_Q105,
                              levels = c('A','B','C'),
                              labels = c( 'Nunca.', 'Poucas vezes.', 'Várias vezes.')),
        TX_RESP_Q106 = factor(TX_RESP_Q106, 
                              levels = c('A','B','C'),
                              labels = c( 'Nunca.', 'Poucas vezes.', 'Várias vezes.')),
        TX_RESP_Q107 = factor(TX_RESP_Q107,
                              levels = c('A','B','C'),
                              labels = c( 'Nunca.', 'Poucas vezes.', 'Várias vezes.')),
        TX_RESP_Q108 = factor(TX_RESP_Q108,
                              levels = c('A','B','C'),
                              labels = c( 'Nunca.', 'Poucas vezes.', 'Várias vezes.')),
        TX_RESP_Q109 = factor(TX_RESP_Q109,
                              levels = c('A','B','C'),
                              labels = c( 'Nunca.', 'Poucas vezes.', 'Várias vezes.')),
        TX_RESP_Q110 = factor(TX_RESP_Q110,
                              levels = c('A','B','C','D','E','F'),
                              labels = c( 'Nunca.', 'Uma vez por ano.', 'De 3 a 4 vezes ao ano.', 'Mensalmente.', 'Semanalmente.', 'Diariamente.')),
        TX_RESP_Q111 = factor(TX_RESP_Q111,
                              levels = c('A','B','C','D','E','F'),
                              labels = c( 'Nunca.', 'Uma vez por ano.', 'De 3 a 4 vezes ao ano.', 'Mensalmente.', 'Semanalmente.', 'Diariamente.')),
        TX_RESP_Q112 = factor(TX_RESP_Q112,
                              levels = c('A','B','C','D','E','F'),
                              labels = c( 'Nunca.', 'Uma vez por ano.', 'De 3 a 4 vezes ao ano.', 'Mensalmente.', 'Semanalmente.', 'Diariamente.')),
        TX_RESP_Q113 = factor(TX_RESP_Q113,
                              levels = c('A','B','C','D','E','F'),
                              labels = c( 'Nunca.', 'Uma vez por ano.', 'De 3 a 4 vezes ao ano.', 'Mensalmente.', 'Semanalmente.', 'Diariamente.')),
        TX_RESP_Q114 = factor(TX_RESP_Q114,
                              levels = c('A','B','C','D','E','F'),
                              labels = c( 'Nunca.', 'Uma vez por ano.', 'De 3 a 4 vezes ao ano.', 'Mensalmente.', 'Semanalmente.', 'Diariamente.')),
        TX_RESP_Q115 = factor(TX_RESP_Q115,
                              levels = c('A','B','C','D','E','F'),
                              labels = c( 'Nunca.', 'Uma vez por ano.', 'De 3 a 4 vezes ao ano.', 'Mensalmente.', 'Semanalmente.', 'Diariamente.')),
        TX_RESP_Q116 = factor(TX_RESP_Q116,
                              levels = c('A','B','C','D','E','F'),
                              labels = c( 'Nunca.', 'Uma vez por ano.', 'De 3 a 4 vezes ao ano.', 'Mensalmente.', 'Semanalmente.', 'Diariamente.')),
        TX_RESP_Q117 = factor(TX_RESP_Q117,
                              levels = c('A','B','C','D','E','F'),
                              labels = c( 'Nunca.', 'Uma vez por ano.', 'De 3 a 4 vezes ao ano.', 'Mensalmente.', 'Semanalmente.', 'Diariamente.')),
        TX_RESP_Q118 = factor(TX_RESP_Q118,
                              levels = c('A','B','C','D','E','F'),
                              labels = c( 'Nunca.', 'Uma vez por ano.', 'De 3 a 4 vezes ao ano.', 'Mensalmente.', 'Semanalmente.', 'Diariamente.')),
        TX_RESP_Q119 = factor(TX_RESP_Q119,
                              levels = c('A','B','C','D','E','F'),
                              labels = c( 'Nunca.', 'Uma vez por ano.', 'De 3 a 4 vezes ao ano.', 'Mensalmente.', 'Semanalmente.', 'Diariamente.')),
        TX_RESP_Q120 = factor(TX_RESP_Q120,
                              levels = c('A','B','C','D','E','F'),
                              labels = c( 'Nunca.', 'Uma vez por ano.', 'De 3 a 4 vezes ao ano.', 'Mensalmente.', 'Semanalmente.', 'Diariamente.')),
        TX_RESP_Q121 = factor(TX_RESP_Q121,
                              levels = c('A','B','C','D','E','F'),
                              labels = c( 'Nunca.', 'Uma vez por ano.', 'De 3 a 4 vezes ao ano.', 'Mensalmente.', 'Semanalmente.', 'Diariamente.')),
        TX_RESP_Q122 = factor(TX_RESP_Q122,
                              levels = c('A','B','C','D','E','F'),
                              labels = c( 'Nunca.', 'Uma vez por ano.', 'De 3 a 4 vezes ao ano.', 'Mensalmente.', 'Semanalmente.', 'Diariamente.')),
        TX_RESP_Q123 = factor(TX_RESP_Q123,
                              levels = c('A','B','C','D','E','F'),
                              labels = c( 'Nunca.', 'Uma vez por ano.', 'De 3 a 4 vezes ao ano.', 'Mensalmente.', 'Semanalmente.', 'Diariamente.')),
        TX_RESP_Q124 = factor(TX_RESP_Q124,
                              levels = c('A','B','C','D','E','F'),
                              labels = c( 'Nunca.', 'Uma vez por ano.', 'De 3 a 4 vezes ao ano.', 'Mensalmente.', 'Semanalmente.', 'Diariamente.')),
        TX_RESP_Q125 = factor(TX_RESP_Q125,
                              levels = c('A','B','C','D','E','F'),
                              labels = c( 'Nunca.', 'Uma vez por ano.', 'De 3 a 4 vezes ao ano.', 'Mensalmente.', 'Semanalmente.', 'Diariamente.')),
        TX_RESP_Q126 = factor(TX_RESP_Q126,
                              levels = c('A','B','C','D','E','F'),
                              labels = c( 'Nunca.', 'Uma vez por ano.', 'De 3 a 4 vezes ao ano.', 'Mensalmente.', 'Semanalmente.', 'Diariamente.')),
        TX_RESP_Q127 = factor(TX_RESP_Q127,
                              levels = c('A','B','C','D','E','F'),
                              labels = c( 'Nunca.', 'Uma vez por ano.', 'De 3 a 4 vezes ao ano.', 'Mensalmente.', 'Semanalmente.', 'Diariamente.')),
        TX_RESP_Q128 = factor(TX_RESP_Q128,
                              levels = c('A','B','C','D','E','F'),
                              labels = c( 'Nunca.', 'Uma vez por ano.', 'De 3 a 4 vezes ao ano.', 'Mensalmente.', 'Semanalmente.', 'Diariamente.'))
  ) %>% 
  rename_with(.cols = starts_with('TX_RESP_'),
              ~ var_names) %>%
  {. ->> saeb_2019_professor}

# Salvar dados limpos ##########################################################
saeb_2019_professor %>% 
  saveRDS(here('data/processed/SAEB/saeb_2019_professor.rds'))
