###############################################
#      ANALISE INSUMO PRODUTO NO RSTUDIO      #
#        ANGELO CUNHA E RENATO CHAVES         #
#                   2022                      #
###############################################

#######################COMENT?RIOS PARA ALTERAR DEPOIS##########################
#              MUDAR AS MATRIZES RECURSOS PARA V E USO PARA U
#
#
#
################################################################################

# CAREGAR PACOTES
{
  install.packages('pacman')
  library(pacman)
  p_load(tidyverse,
         janitor,
         here)
}

# IMPORTANDO ARQUIVOS####
# MATRIZ INSUMO PRODUTO
# https://www.ibge.gov.br/estatisticas/economicas/contas-nacionais/9085-matriz-de-insumo-produto.html?=&t=resultados

# Download do arquivo
download.file(url = "https://ftp.ibge.gov.br/Contas_Nacionais/Matriz_de_Insumo_Produto/2015/Matriz_de_Insumo_Produto_2015_Nivel_12.xls",
              destfile = here('Matriz_de_Insumo_Produto_2015_Nivel_12.xls'),
              mode = "wb")

#MATRIZ 12 SETORES####

#TABELA DE RECURSOS####
# Importar arquivo
MATRIZ_12_SETORES_RECURSOS <- readxl::read_excel(here('Matriz_de_Insumo_Produto_2015_Nivel_12.xls'),
                                                 sheet = '01',
                                                 trim_ws = T,
                                                 skip = 3,
                                                 n_max = 13,
                                                 col_types = 'text') %>%
  # Consertar nomes das colunas
  janitor::clean_names() %>%
  # retirar NAs
  drop_na() %>%
  # Mudar tipos e renomear as colunas
  mutate(across(oferta_total_a_preco_de_consumidor:total_do_produto, as.numeric),
         codigo_do_produto_nivel_12 = as.numeric(x1),
         descricao_do_produto_nivel_12 = x2,
         importacao_bens_servicos = as.numeric(x21),
         .keep = 'unused') %>%
  # trazer as colunas para locais corretos
  relocate(codigo_do_produto_nivel_12,
           descricao_do_produto_nivel_12)

MATRIZ_12_SETORES_RECURSOS = read_excel("Matriz_de_Insumo_Produto_2015_Nivel_12.xls", sheet='01')

#EXCLUIDO LINHAS E COLUNAS
LINHAS_RECURSOS = c(1,2,3,4,17,18,19,20,21)
COLUNA_RECURSOS = c(1,2,3,4,5,6,7,20,21)
MATRIZ_12_SETORES_RECURSOS = MATRIZ_12_SETORES_RECURSOS[-LINHAS_RECURSOS,-COLUNA_RECURSOS]


#RENOMEANDO LINHAS E COLUNAS
dimnames(MATRIZ_12_SETORES_RECURSOS) <- list(c("P1", "P2","P3", "P4", "P5", "P6", "P7","P8", "P9", "P10", "P11", "P12"),
                           c("S1", "S2", "S3", "S4", "S5","S6", "S7", "S8", "S9", "S10","S11","S12"))

#TRANSFORMANDO DATA.FRAME EM MATRIZ
MATRIZ_12_SETORES_RECURSOS = as.matrix(MATRIZ_12_SETORES_RECURSOS)


#TRANSPONDO A MATRIZ
MATRIZ_12_SETORES_RECURSOS = t(MATRIZ_12_SETORES_RECURSOS)


#RETIRANDO INFORMACOES DA MATRIZ DE RECURSOS####
#VALOR BRUTO TOTAL####
VBP_TOTAL_LINHAS = sum(as.integer(MATRIZ_12_SETORES_RECURSOS[1:12,]))
VBP_TOTAL_COLUNAS = sum(as.integer(MATRIZ_12_SETORES_RECURSOS[,1:12]))

#VALOR BRUTO DA PRODUCAO####
VBP_POR_SETOR_1 = sum(as.integer(MATRIZ_12_SETORES_RECURSOS[1,]))
VBP_POR_SETOR_1
VBP_POR_SETOR_2 = sum(as.integer(MATRIZ_12_SETORES_RECURSOS[2,]))
VBP_POR_SETOR_2
VBP_POR_SETOR_3 = sum(as.integer(MATRIZ_12_SETORES_RECURSOS[3,]))
VBP_POR_SETOR_3
VBP_POR_SETOR_4 = sum(as.integer(MATRIZ_12_SETORES_RECURSOS[4,]))
VBP_POR_SETOR_4
VBP_POR_SETOR_5 = sum(as.integer(MATRIZ_12_SETORES_RECURSOS[5,]))
VBP_POR_SETOR_5
VBP_POR_SETOR_6 = sum(as.integer(MATRIZ_12_SETORES_RECURSOS[6,]))
VBP_POR_SETOR_6
VBP_POR_SETOR_7 = sum(as.integer(MATRIZ_12_SETORES_RECURSOS[7,]))
VBP_POR_SETOR_7
VBP_POR_SETOR_8 = sum(as.integer(MATRIZ_12_SETORES_RECURSOS[8,]))
VBP_POR_SETOR_8
VBP_POR_SETOR_9 = sum(as.integer(MATRIZ_12_SETORES_RECURSOS[9,]))
VBP_POR_SETOR_9
VBP_POR_SETOR_10 = sum(as.integer(MATRIZ_12_SETORES_RECURSOS[10,]))
VBP_POR_SETOR_10
VBP_POR_SETOR_11 = sum(as.integer(MATRIZ_12_SETORES_RECURSOS[11,]))
VBP_POR_SETOR_11
VBP_POR_SETOR_12 = sum(as.integer(MATRIZ_12_SETORES_RECURSOS[12,]))
VBP_POR_SETOR_12

#VALOR DA PRODUCAO DOR PRODUTO####
VALOR_PRODUCAO_PRODUTO_1 = sum(as.integer(MATRIZ_12_SETORES_RECURSOS[,1]))
VALOR_PRODUCAO_PRODUTO_1
VALOR_PRODUCAO_PRODUTO_2 = sum(as.integer(MATRIZ_12_SETORES_RECURSOS[,2]))
VALOR_PRODUCAO_PRODUTO_2
VALOR_PRODUCAO_PRODUTO_3 = sum(as.integer(MATRIZ_12_SETORES_RECURSOS[,3]))
VALOR_PRODUCAO_PRODUTO_3
VALOR_PRODUCAO_PRODUTO_4 = sum(as.integer(MATRIZ_12_SETORES_RECURSOS[,4]))
VALOR_PRODUCAO_PRODUTO_4
VALOR_PRODUCAO_PRODUTO_5 = sum(as.integer(MATRIZ_12_SETORES_RECURSOS[,5]))
VALOR_PRODUCAO_PRODUTO_5
VALOR_PRODUCAO_PRODUTO_6 = sum(as.integer(MATRIZ_12_SETORES_RECURSOS[,6]))
VALOR_PRODUCAO_PRODUTO_6
VALOR_PRODUCAO_PRODUTO_7 = sum(as.integer(MATRIZ_12_SETORES_RECURSOS[,7]))
VALOR_PRODUCAO_PRODUTO_7
VALOR_PRODUCAO_PRODUTO_8 = sum(as.integer(MATRIZ_12_SETORES_RECURSOS[,8]))
VALOR_PRODUCAO_PRODUTO_8
VALOR_PRODUCAO_PRODUTO_9 = sum(as.integer(MATRIZ_12_SETORES_RECURSOS[,9]))
VALOR_PRODUCAO_PRODUTO_9
VALOR_PRODUCAO_PRODUTO_10 = sum(as.integer(MATRIZ_12_SETORES_RECURSOS[,10]))
VALOR_PRODUCAO_PRODUTO_10
VALOR_PRODUCAO_PRODUTO_11 = sum(as.integer(MATRIZ_12_SETORES_RECURSOS[,11]))
VALOR_PRODUCAO_PRODUTO_11
VALOR_PRODUCAO_PRODUTO_12 = sum(as.integer(MATRIZ_12_SETORES_RECURSOS[,12]))
VALOR_PRODUCAO_PRODUTO_12

#TABELA DE RECURSOS COMPLETA####
MATRIZ_12_SETORES_RECURSOS = rbind(MATRIZ_12_SETORES_RECURSOS, c(VALOR_PRODUCAO_PRODUTO_1,VALOR_PRODUCAO_PRODUTO_2,VALOR_PRODUCAO_PRODUTO_3,
                                VALOR_PRODUCAO_PRODUTO_4,VALOR_PRODUCAO_PRODUTO_5,VALOR_PRODUCAO_PRODUTO_6,VALOR_PRODUCAO_PRODUTO_7,
                                VALOR_PRODUCAO_PRODUTO_8,VALOR_PRODUCAO_PRODUTO_9,VALOR_PRODUCAO_PRODUTO_10,VALOR_PRODUCAO_PRODUTO_11,
                                VALOR_PRODUCAO_PRODUTO_12))


MATRIZ_12_SETORES_RECURSOS = cbind(MATRIZ_12_SETORES_RECURSOS,c(VBP_POR_SETOR_1,VBP_POR_SETOR_2,VBP_POR_SETOR_3,
                                VBP_POR_SETOR_4,VBP_POR_SETOR_5,VBP_POR_SETOR_6,VBP_POR_SETOR_7,VBP_POR_SETOR_8,
                                VBP_POR_SETOR_9,VBP_POR_SETOR_10,VBP_POR_SETOR_11,VBP_POR_SETOR_12,VBP_TOTAL_COLUNAS))

dimnames(MATRIZ_12_SETORES_RECURSOS) <- list(c("P1", "P2","P3", "P4", "P5", "P6", "P7","P8", "P9", "P10", "P11", "P12","VALOR_BRUTO_DA_PRODU??O"),
                                             c("S1", "S2", "S3", "S4", "S5","S6", "S7", "S8", "S9", "S10","S11","S12","VALOR_PRODU??O_DO_PRODUTO"))


View(MATRIZ_12_SETORES_RECURSOS)

#TABELA D - MARKET SHARE####

#SEPARO OS VALORES DA PRODUCAO POR PRODUTO E DA MATRIZ COM 12 SETORES E 12 PRODUTOS
VALOR_DA_PRODUCAO_POR_SETOR = MATRIZ_12_SETORES_RECURSOS[13,1:12]
MATRIZ_12_RECURSOS = MATRIZ_12_SETORES_RECURSOS[1:12,1:12]

#TRANSFORMO OS CHARACTERS EM NUMERICOS
VALOR_DA_PRODUCAO_POR_SETOR = as.numeric(VALOR_DA_PRODUCAO_POR_SETOR)
MATRIZ_12_RECURSOS = as.numeric(MATRIZ_12_RECURSOS)

#FAZ MA REPETICAO DO TOTAL PARA FAZER UMA MATRIZ DO MESMO TAMANHO DA MATRIZ 12 RECURSOS COM VALORES DA
#PRODUCAO POR PRODUTO PARA EMS EGUIDA FAZER A DIVIS?O DE UMA MATRIZ POR OUTRA. E POR FIM ARREDONDO PARA 4 CASAS
REPTOTAL_D = rep(VALOR_DA_PRODUCAO_POR_SETOR, length(MATRIZ_12_RECURSOS) / length(VALOR_DA_PRODUCAO_POR_SETOR))
MARKET_SHARE_D = MATRIZ_12_RECURSOS / t(matrix(REPTOTAL_D, ncol=12))
MARKET_SHARE_D = round(MARKET_SHARE_D,4)

#RENOMEIO A MATRIZ
dimnames(MARKET_SHARE_D) <- list(c("S1", "S2", "S3", "S4", "S5","S6", "S7", "S8", "S9", "S10","S11","S12"),
                                 c("P1", "P2","P3", "P4", "P5", "P6", "P7","P8", "P9", "P10", "P11", "P12"))

MARKET_SHARE_D = as.matrix(MARKET_SHARE_D)

MATRIZ_12_RECURSOS = MATRIZ_12_SETORES_RECURSOS[1:12,1:12]
MATRIZ_12_RECURSOS = as.matrix(MATRIZ_12_RECURSOS)

#TABELA DE USOS####


MATRIZ_12_SETORES_USOS = read_excel("Matriz_de_Insumo_Produto_2015_Nivel_12.xls", sheet='03')

#EXCLUIDO LINHAS E COLUNAS
LINHAS_USOS = c(1,2,3,4,17,18,19,20)
COLUNA_USOS = c(1,2,3,16,17,18,19,20,21,22,23,24)
MATRIZ_12_SETORES_USOS = MATRIZ_12_SETORES_USOS[-LINHAS_USOS,-COLUNA_USOS]


#RENOMEANDO LINHAS E COLUNAS
dimnames(MATRIZ_12_SETORES_USOS) <- list(c("P1", "P2","P3", "P4", "P5", "P6", "P7","P8", "P9", "P10", "P11", "P12"),
                                             c("S1", "S2", "S3", "S4", "S5","S6", "S7", "S8", "S9", "S10","S11","S12"))

#TRANSFORMANDO DATA.FRAME EM MATRIZ
MATRIZ_12_SETORES_USOS = as.matrix(MATRIZ_12_SETORES_USOS)


#RETIRANDO INFORMACOES DA MATRIZ DE RECURSOS####
#VALOR BRUTO TOTAL####
CONSUMO_TOTAL_CONSUMO_NACIONAL_LINHAS = sum(as.integer(MATRIZ_12_SETORES_USOS[1:12,]))
CONSUMO_TOTAL_CONSUMO_NACIONAL_COLUNAS = sum(as.integer(MATRIZ_12_SETORES_USOS[,1:12]))

#VALOR BRUTO DA PRODUCAO####
SAIDA_INTERMED_PRODUTO_1 = sum(as.integer(MATRIZ_12_SETORES_USOS[1,]))
SAIDA_INTERMED_PRODUTO_1
SAIDA_INTERMED_PRODUTO_2 = sum(as.integer(MATRIZ_12_SETORES_USOS[2,]))
SAIDA_INTERMED_PRODUTO_2
SAIDA_INTERMED_PRODUTO_3 = sum(as.integer(MATRIZ_12_SETORES_USOS[3,]))
SAIDA_INTERMED_PRODUTO_3
SAIDA_INTERMED_PRODUTO_4 = sum(as.integer(MATRIZ_12_SETORES_USOS[4,]))
SAIDA_INTERMED_PRODUTO_4
SAIDA_INTERMED_PRODUTO_5 = sum(as.integer(MATRIZ_12_SETORES_USOS[5,]))
SAIDA_INTERMED_PRODUTO_5
SAIDA_INTERMED_PRODUTO_6 = sum(as.integer(MATRIZ_12_SETORES_USOS[6,]))
SAIDA_INTERMED_PRODUTO_6
SAIDA_INTERMED_PRODUTO_7 = sum(as.integer(MATRIZ_12_SETORES_USOS[7,]))
SAIDA_INTERMED_PRODUTO_7
SAIDA_INTERMED_PRODUTO_8 = sum(as.integer(MATRIZ_12_SETORES_USOS[8,]))
SAIDA_INTERMED_PRODUTO_8
SAIDA_INTERMED_PRODUTO_9= sum(as.integer(MATRIZ_12_SETORES_USOS[9,]))
SAIDA_INTERMED_PRODUTO_9
SAIDA_INTERMED_PRODUTO_10 = sum(as.integer(MATRIZ_12_SETORES_USOS[10,]))
SAIDA_INTERMED_PRODUTO_10
SAIDA_INTERMED_PRODUTO_11 = sum(as.integer(MATRIZ_12_SETORES_USOS[11,]))
SAIDA_INTERMED_PRODUTO_11
SAIDA_INTERMED_PRODUTO_12 = sum(as.integer(MATRIZ_12_SETORES_USOS[12,]))
SAIDA_INTERMED_PRODUTO_12

#VALOR DA PRODUCAO DOR PRODUTO####
INSUMO_NACIONAL_DO_SETOR_1 = sum(as.integer(MATRIZ_12_SETORES_USOS[,1]))
INSUMO_NACIONAL_DO_SETOR_1
INSUMO_NACIONAL_DO_SETOR_2 = sum(as.integer(MATRIZ_12_SETORES_USOS[,2]))
INSUMO_NACIONAL_DO_SETOR_2
INSUMO_NACIONAL_DO_SETOR_3 = sum(as.integer(MATRIZ_12_SETORES_USOS[,3]))
INSUMO_NACIONAL_DO_SETOR_3
INSUMO_NACIONAL_DO_SETOR_4 = sum(as.integer(MATRIZ_12_SETORES_USOS[,4]))
INSUMO_NACIONAL_DO_SETOR_4
INSUMO_NACIONAL_DO_SETOR_5 = sum(as.integer(MATRIZ_12_SETORES_USOS[,5]))
INSUMO_NACIONAL_DO_SETOR_5
INSUMO_NACIONAL_DO_SETOR_6 = sum(as.integer(MATRIZ_12_SETORES_USOS[,6]))
INSUMO_NACIONAL_DO_SETOR_6
INSUMO_NACIONAL_DO_SETOR_7 = sum(as.integer(MATRIZ_12_SETORES_USOS[,7]))
INSUMO_NACIONAL_DO_SETOR_7
INSUMO_NACIONAL_DO_SETOR_8 = sum(as.integer(MATRIZ_12_SETORES_USOS[,8]))
INSUMO_NACIONAL_DO_SETOR_8
INSUMO_NACIONAL_DO_SETOR_9 = sum(as.integer(MATRIZ_12_SETORES_USOS[,9]))
INSUMO_NACIONAL_DO_SETOR_9
INSUMO_NACIONAL_DO_SETOR_10 = sum(as.integer(MATRIZ_12_SETORES_USOS[,10]))
INSUMO_NACIONAL_DO_SETOR_10
INSUMO_NACIONAL_DO_SETOR_11 = sum(as.integer(MATRIZ_12_SETORES_USOS[,11]))
INSUMO_NACIONAL_DO_SETOR_11
INSUMO_NACIONAL_DO_SETOR_12 = sum(as.integer(MATRIZ_12_SETORES_USOS[,12]))
INSUMO_NACIONAL_DO_SETOR_12

MATRIZ_12_SETORES_USOS = rbind(MATRIZ_12_SETORES_USOS, c(INSUMO_NACIONAL_DO_SETOR_1,INSUMO_NACIONAL_DO_SETOR_2,INSUMO_NACIONAL_DO_SETOR_3,
                                                         INSUMO_NACIONAL_DO_SETOR_4,INSUMO_NACIONAL_DO_SETOR_5,INSUMO_NACIONAL_DO_SETOR_6,INSUMO_NACIONAL_DO_SETOR_7,
                                                         INSUMO_NACIONAL_DO_SETOR_8,INSUMO_NACIONAL_DO_SETOR_9,INSUMO_NACIONAL_DO_SETOR_10,INSUMO_NACIONAL_DO_SETOR_11,
                                                         INSUMO_NACIONAL_DO_SETOR_12))


MATRIZ_12_SETORES_USOS = cbind(MATRIZ_12_SETORES_USOS,c(SAIDA_INTERMED_PRODUTO_1,SAIDA_INTERMED_PRODUTO_2,SAIDA_INTERMED_PRODUTO_3,
                                                        SAIDA_INTERMED_PRODUTO_4,SAIDA_INTERMED_PRODUTO_5,SAIDA_INTERMED_PRODUTO_6,SAIDA_INTERMED_PRODUTO_7,SAIDA_INTERMED_PRODUTO_8,
                                                        SAIDA_INTERMED_PRODUTO_9,SAIDA_INTERMED_PRODUTO_10,SAIDA_INTERMED_PRODUTO_11,SAIDA_INTERMED_PRODUTO_12,CONSUMO_TOTAL_CONSUMO_NACIONAL_COLUNAS))



View(MATRIZ_12_SETORES_USOS)
dimnames(MATRIZ_12_SETORES_USOS) <- list(c("P1", "P2","P3", "P4", "P5", "P6", "P7","P8", "P9", "P10", "P11", "P12","VALOR_INSUMOS_NACIONAIS"),
                                         c("S1", "S2", "S3", "S4", "S5","S6", "S7", "S8", "S9", "S10","S11","S12","VALOR_SAIDA_INTERMERD"))


#TABELA B - COEFICIENTES TECNICOS DE INSUMOS NACIONAIS####

#SEPARO OS VALORES DA PRODUCAO POR PRODUTO E DA MATRIZ COM 12 SETORES E 12 PRODUTOS
VALOR_BRUTO_PRODUCAO_POR_SETOR = MATRIZ_12_SETORES_RECURSOS[1:12,13]
MATRIZ_12_USOS = MATRIZ_12_SETORES_USOS[1:12,1:12]

#TRANSFORMO OS CHARACTERS EM NUMERICOS
VALOR_BRUTO_PRODUCAO_POR_SETOR = as.numeric(VALOR_BRUTO_PRODUCAO_POR_SETOR)
MATRIZ_12_USOS = as.numeric(MATRIZ_12_USOS)

#FAZ MA REPETICAO DO TOTAL PARA FAZER UMA MATRIZ DO MESMO TAMANHO DA MATRIZ 12 RECURSOS COM VALORES DA
#PRODUCAO POR PRODUTO PARA EMS EGUIDA FAZER A DIVIS?O DE UMA MATRIZ POR OUTRA. E POR FIM ARREDONDO PARA 4 CASAS
REPTOTAL_B = rep(VALOR_BRUTO_PRODUCAO_POR_SETOR, length(MATRIZ_12_USOS) / length(VALOR_BRUTO_PRODUCAO_POR_SETOR))
COEF_INSUMOS_NACIONAIS_B = MATRIZ_12_USOS / t(matrix(REPTOTAL_B, ncol=12))
COEF_INSUMOS_NACIONAIS_B = round(COEF_INSUMOS_NACIONAIS_B,4)

#RENOMEIO A MATRIZ
dimnames(COEF_INSUMOS_NACIONAIS_B) <- list(c("P1", "P2","P3", "P4", "P5", "P6", "P7","P8", "P9", "P10", "P11", "P12"),
                                           c("S1", "S2", "S3", "S4", "S5","S6", "S7", "S8", "S9", "S10","S11","S12"))

COEF_INSUMOS_NACIONAIS_B = as.matrix(COEF_INSUMOS_NACIONAIS_B)

MATRIZ_12_USOS = MATRIZ_12_SETORES_USOS[1:12,1:12]
MATRIZ_12_USOS = as.matrix(MATRIZ_12_USOS)

#MATRIZES CALCULADAS####
View(MATRIZ_12_SETORES_RECURSOS)
View(MATRIZ_12_RECURSOS)
View(MARKET_SHARE_D)
View(MATRIZ_12_SETORES_USOS)
View(MATRIZ_12_USOS)
View(COEF_INSUMOS_NACIONAIS_B)


#MATRIZ Z####
#A MATRIZ Z PODE SER ENCONTRADA A PARTIR DA MULTIPLICACAO DAS MATRIZES D E U
#COMO SAO DA MESMA DIMENSAO PODEMOS MULTIPLICAR
#PARA MULTIPLICAR AS MATRIZES USAMOS O COMANDO %*%


MATRIZ_Z = MARKET_SHARE_D %*% MATRIZ_12_USOS
View(MATRIZ_Z)

#COEFICIENTES TECNICOS DA MATRIZ Z####

#PELAS MATRIZES D E B####

COEFI_Z_POR_DB = MARKET_SHARE_D %*% COEF_INSUMOS_NACIONAIS_B
COEFI_Z_POR_DB = round(COEFI_Z_POR_DB,4)

#PELA MATRIZ Z E VBP####

REPTOTAL_Z = rep(VALOR_BRUTO_PRODUCAO_POR_SETOR, length(MATRIZ_Z) / length(VALOR_BRUTO_PRODUCAO_POR_SETOR))
MATRIZ_A = MATRIZ_Z / t(matrix(REPTOTAL_B, ncol=12))
MATRIZ_A = round(MATRIZ_A,4)


#MATRIZ 68 SETORES####

#SISTEMA DE CONTAS NACIONAIS####
#https://www.ibge.gov.br/estatisticas/economicas/contas-nacionais/9052-sistema-de-contas-nacionais-brasil.html?=&t=resultados



















